@userId= 634259d47262baf808e9ab78

### GET USERS
GET http://localhost:4001/api/v1/users?role=MENTOR_ROLE

### CREATE USER
POST http://localhost:4001/api/v1/users HTTP/1.1
content-type: application/json

{
    "name": "Abel Valeriano",
    "password": "123456",
    "email": "abel@hotmail.cccsd",
    "role": "MENTOR_ROLE"
}

### UPDATE USER
PATCH http://localhost:4001/api/v1/users/{{userId}} HTTP/1.1
content-type: application/json

{

}

### LOGIN USER
POST http://localhost:4001/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "abel@gmail.com",
    "password": "123456"
}