@userId= 633123bbc4840ae0bb66a3eb

### GET USERS
GET http://localhost:4001/api/v1/users

### CREATE USER
POST http://localhost:4001/api/v1/users HTTP/1.1
content-type: application/json

{
    "name": "Abel Valeriano",
    "password": "123456",
    "email": "abel@gmail.com",
    "role": "MENTOR_ROLE"
}

### UPDATE USER
PATCH http://localhost:4001/api/v1/users/{{userId}} HTTP/1.1
content-type: application/json

{
    "name": "Leonardo Valeriano Macuri"
}

### LOGIN USER
POST http://localhost:4001/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "abel@gmail.com",
    "password": "123456"
}