version: '3.8'

services:
  api:
    container_name: feddingminds_api
    restart: always
    build: .
    ports:
      - '4001:4001'
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo/feedingmindsdb
      - PORT=4001
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=465
      - MAIL_USERNAME=feedingminds.pe@gmail.com
      - MAIL_PASSWORD=APPLICATION_PASSWORD
      - MAIL_SECURE=true
      - MAIL_FROM_ADDRESS=feedingminds.pe@gmail.com
      - MAIL_FROM_NAME="Feeding Minds"
  mongo:
    container_name: mongo_container
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - ./mongodb_data_container:/data/db
